version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: motioneye_server_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"

  web:
    image: ccrisan/motioneye:master-amd64
    init: true
    hostname: "${DEVICE_HOSTNAME}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/config:/etc/motioneye
      - ${APP_DATA_DIR}/data/storage:/var/lib/motioneye
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - port=9001
