version: "3.7"

services:
  web:
    image: ccrisan/motioneye:master-amd64
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/config:/etc/motioneye
      - ${APP_DATA_DIR}/data/storage:/var/lib/motioneye
    restart: always
    ports:
      - "8081:8081"
      - "8765:8765"
